### ISSUE TITLE
Access the room id from inside a plugin

### ISSUE THREAD

**Issue by failshell** [justinweiss/robut#51]
Is it possible to get the room ID from inside a plugin?

I'd like to restrict some plugins to some rooms.

Also, is it possible to access the user JID as well from within a plugin?

**Comment by justinweiss** [comment]
I thought there was, but it’s been a while since I’ve looked at that code. I should have a chance to check it out later this week.

**Comment by failshell** [comment]
Yeah seems like the project is pretty much dead :)

**Comment by justinweiss** [comment]
It keeps trucking along! Most of my work on it goes into plugins these days, though :-)

**Comment by gerardepema** [comment]
Any update on this?
I'm looking for a way to access the room (id|name) within a class
How, in the below sample would I get access to the room name/id?

Sample:
class Robut::Plugin::Flipbot < Robut::Presence
  include Robut::Plugin

  def handle(time, sender_nick, message)

```
# print "message received" if message["user"]

reply("Test") if message["@flipbot test"]
```

  end
end

**Comment by justinweiss** [comment]
Nope, no progress — this has slipped way down on my priority list. I don’t believe it would be too hard to add, but we’d want to make sure we don’t break existing plugins.

**Comment by gerardepema** [comment]
Hi Justin,

Sorry for bothering you again. 
I've been reading up on the post on how to figure out how to join rooms with some code written by Will Leinweber. 
You mentioned you got it working and I applied the code changes but I don't know where or how to add the 'loop' code to bin/robut for it to act on the room invites. 

Can you supply me with a working sample of bin/robut?

Thanks,
Gerard
